# Generated by Django 5.2 on 2026-05-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_choices_alter_listing_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
