# Generated by Django 5.2 on 2026-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('listings', '0003_alter_listing_description_alter_listing_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-list_date']},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_List_da_6dbaa7_idx',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='List_date',
            new_name='list_date',
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-list_date'], name='listings_li_list_da_a9392b_idx'),
        ),
    ]
